model:
  target: modules.model.DummyModel
  params:
    lr: 0.0001

data:
  target: modules.data.datamodule.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 16
    train:
      target: modules.data.DummyData
      params:
        file_path: 
    validation:
      target: modules.data.DummyData
      params:
        file_path: 
    test:
      target: modules.data.DummyData
      params:
        file_path: 

custom_callback:
  cuda_callback:
    target: modules.callbacks.CUDACallback
