model:
  target: modules.model.TransformerP2T
  params:
    base_learning_rate: 0.001 
    monitor: valid/loss 
    d_model: 512 
    nhead: 4 
    dim_feedforward: 1024
    activation: relu
    n_layers: 2
    emb_dim: 512
    max_len: 150
    text_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/train.text
    gloss_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/train.gloss
    text_vocab_cache: /home/ejhwang/plsl/cache/text_vocab.json
    gloss_vocab_cache: /home/ejhwang/plsl/cache/gloss_vocab.json
    vocab_freq: 1

data:
  target: modules.datamodule.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 16
    train:
      target: modules.data.Phoenix2014T
      params:
        text_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/train.text
        gloss_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/train.gloss
        keypoint_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/train.skels
    validation:
      target: modules.data.Phoenix2014T
      params:
        text_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/dev.text
        gloss_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/dev.gloss
        keypoint_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/dev.skels 
    test:
      target: modules.data.Phoenix2014T
      params:
        text_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/test.text
        gloss_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/test.gloss
        keypoint_file_path: /data/sl_datasets/phoenix14t/data/ProgressiveTransformersSLP/test.skels 